#!/usr/bin/env bash

ghostty() {
	rm $XDG_CONFIG_HOME/ghostty/themes/theme
	ln -s $HOME/Personal/myland/$1/ghostty/* $XDG_CONFIG_HOME/ghostty/themes
}

kitty() {
	rm $XDG_CONFIG_HOME/kitty/theme.conf
	ln -s $HOME/Personal/myland/$1/kitty/* $XDG_CONFIG_HOME/kitty/
}

hypr() {
	rm $XDG_CONFIG_HOME/hypr/theme.conf
	ln -s $HOME/Personal/myland/$1/hypr/theme.conf $XDG_CONFIG_HOME/hypr/
}

waybar() {
	rm $XDG_CONFIG_HOME/waybar/theme.css
	ln -s $HOME/Personal/myland/$1/waybar/theme.css $XDG_CONFIG_HOME/waybar/
}

btop() {
	rm $XDG_CONFIG_HOME/btop/themes/*
	ln -s $HOME/Personal/myland/$1/btop/*.theme $XDG_CONFIG_HOME/btop/themes/
}

waybar "$1"
hypr "$1"
kitty "$1"
btop "$1"
ghostty "$1"

killall waybar
/usr/bin/waybar &
kill -SIGUSR1 $(pgrep kitty)
hyprctl reload
